### ISSUE TITLE
Editing the Readme

### ISSUE THREAD

**Issue by NickoM31** [odiseoteam/SyliusMailchimpPlugin#1]
In your Readme / installation, it seems to me that the path and name of the plugin that we add in bundles.php are not the right ones. Instead of \ Odiseo \ SyliusReportPlugin \ OdiseoSyliusReportPlugin () it's Odiseo \ SyliusMailchimpPlugin \ OdiseoSyliusMailchimpPlugin

**Comment by odiseoteam** [comment]
Fixed! Thanks @NickoM31 . How do you see the plugin?

**Comment by NickoM31** [comment]
Hello @odiseoteam ,
It is a great pleasure to contribute.
This plugin is complete but I still have some problem to use it, especially for the newsletter. I think I will come back to you very soon for more information. I noticed another problem and I will create an Issue.
Cordially.
Nicko

**Comment by odiseoteam** [comment]
Hi @NickoM31 , let me know if you still having problem and feel free to create a PR if not. Thanks for your feedback!

**Comment by NickoM31** [comment]
Hi guys ! Everything goes well with your plugin.If I see other bugs I will
make you go back. You are doing a good job. See ya !

**Comment by songecko** [comment]
Thank you @NickoM31 . It's a pleasure to know that you found it useful.
